# Generated by Django 3.0 on 2021-04-24 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('A', 'Vegetables'), ('B', 'Fruits')], max_length=10)),
                ('item_name', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('impf', models.ImageField(default='farmer logo.png', upload_to='farmers/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_farmer', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=10)),
                ('mobile_number', models.CharField(default='', max_length=12)),
                ('impf', models.ImageField(default='farmer logo.png', upload_to='images/')),
                ('address', models.CharField(default='', max_length=100)),
                ('u', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
