# Generated by Django 3.0 on 2021-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0004_auto_20210424_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extpro',
            name='impf',
            field=models.ImageField(default='user logo.png', upload_to='pro/'),
        ),
    ]
